### ISSUE TITLE
Filter dialog box not displaying correctly

### ISSUE THREAD

**Issue by jphillips-bp3** [apromore/ApromoreCore#195]
Hi,

I have imported the attached CSV file and converted to XES. However when I generate the process model and then try and create a filter, the filter dialog box does not display correctly. It appears down in the bottom left hand area of the screen and the End Time field is highlighted in red. That implies a data issue but looking through my CSV file I cannot see anything obvious. Could you take a look and see where you think the issue is, thanks?

![image](https://user-images.githubusercontent.com/4510278/59617672-ab454200-911e-11e9-9dff-fd2a71a7e528.png)

[process-data.csv.zip](https://github.com/apromore/ApromoreCore/files/3297758/process-data.csv.zip)

**Comment by verenich** [comment]
Hi,

I could not reproduce this issue (check the screenshot). Most likely, it has been caused by incorrect timestamp handling. When importing a CSV file, you should *manually* specify the timestamp format as yyyy-MM-dd'T'HH:mm:ss.SSS in your case
![Untitled](https://user-images.githubusercontent.com/5514861/60319519-03e7cb00-99ba-11e9-9f1c-6bfa29286fc2.png)

**Comment by jphillips-bp3** [comment]
This is now working on v7.2.0 using the date / time format `yyyy-MM-dd'T'HH:mm:ss.SSS` so can be closed.
